sonar.projectKey=saleor-backend
sonar.projectName=saleor-backend
sonar.sourceEncoding=UTF-8

# Rutas típicas del repo
sonar.sources=saleor
sonar.tests=tests

# Excluir ruido
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/*.pyc,**/.venv/**

# Reportes de pruebas/cobertura (si existen)
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=pytest.xml
